				#include <p18f452.inc>
				CONFIG	WDT = OFF
				LIST	P = 18F452	
				RADIX 	HEX
				ORG		0x00000
				BSF		TRISA,TRISA0
				CLRF	TRISD,0
				CLRF	TRISE,0
				MOVLW	0x41
				MOVWF	ADCON0
				MOVLW	0x82
				MOVWF	ADCON1
REPEAT
				CALL	CAPACITOR_TIME
				BSF		ADCON0,GO
HERE
				BTFSC	ADCON0,GO
				GOTO	HERE
				MOVF	ADRESL,W
				MOVWF	LATD
				MOVF	ADRESH,W
				MOVWF	LATE
				GOTO	REPEAT
CAPACITOR_TIME
				MOVLW	0x48
				MOVWF	T0CON
				MOVLW	D'236'	
				MOVWF	TMR0L
				BCF		INTCON,TMR0IF
				BSF		T0CON,TMR0ON
MONITOR		
				BTFSS	INTCON,TMR0IF
				GOTO	MONITOR
				BCF		INTCON,TMR0IF
				BCF		T0CON,TMR0ON
				RETURN
				END