			#include <p18f452.inc>
			CONFIG	WDT = OFF
			LIST	P = 18F452	
			RADIX	HEX
POSITION	EQU		0x000
VALUE		EQU		0x001
CONST		EQU		0x002
TEMP_1		EQU		0x003
TEMP_2		EQU		0x004

			ORG		0x00000
			CLRF	TRISD,0
HOME
			CLRF	TEMP_1,0
			CLRF	TEMP_2,0
			CLRF	POSITION,0
			CLRF	VALUE,0
			MOVLW	0x01
			MOVWF	CONST,0
REPEAT
			MOVF	POSITION,W,0		
			XORLW	0x08
			BZ		HOME		
			CALL	ROTATE
			MOVF	TEMP_2,W			
			IORWF	VALUE,F,0
			MOVF	VALUE,W
			MOVWF	LATD
			INCF	POSITION,F,0
			CALL	DELAY
			GOTO	REPEAT
ROTATE	
			MOVF	POSITION,W
			MOVWF	TEMP_1,0
			MOVF	CONST,W
			MOVWF	TEMP_2,0
IS_IT_ZERO
			MOVF	TEMP_1,W
			XORLW	0x00				
			BTFSC	STATUS,Z
			RETURN
			RLCF	TEMP_2,F,0
			DECF	TEMP_1,F,0		
			GOTO	IS_IT_ZERO	
DELAY
			MOVLW	0x07
			MOVWF	T0CON
			MOVLW	0xF8
			MOVWF	TMR0H
			MOVLW	0x57
			MOVWF	TMR0L	
			BCF		INTCON,TMR0IF
			BSF		T0CON,TMR0ON
MONITOR
			BTFSS	INTCON,TMR0IF
			GOTO	MONITOR
			BCF		INTCON,TMR0IF
			BCF		T0CON,TMR0ON	
			RETURN		
			END