; ASSEMBLY SOURCE CODE FOR A BCD/7 SEGMENT DISPLAY
; THE ASSEMBLY CODE IS USED TO DISPLAY NUMBERS FROM 00 TO 99 USING PUSH BUTTON (PORTB, RB0)
; THE CODE HAS BEEN VERIFIED BY SIMULATION USING PROTEUS ISIS
; BUTTON IS CONNECTED WITH PIN (RB0) OF PORTB
; THE BCD/7 SEGMENT IS CONNECTED WITH PINS(RD0-RD3) OF PORTD
; THE PORTE IS USED TO CONTROLLE WHICH ONE DISPLAYS THE NUMBER
; THIS METHODE DOES NOT USE INTERRUPTS ONLY POLLING METHODE (BY KEEPING MONITORING THE STATE OF PIN CONNECTED TO THE EXTERNAL BUTTON)
; AND ALSO KEEP MONITORING THE INTERRUPT FLAG BIT (TMR0IF)
; PROGRAMMER : DALI FETHI ABDELLATIF
; DATE : 01/02/2024
;-------------------------------------------------------------------------------------------------
			CONFIG		WDT = OFF	
			#INCLUDE	<p18f452.inc>
			LIST 		P = 18F452
COUNTER		EQU			0x00
HIG			EQU			0x01
LOWE		EQU			0x02
;-------------	STARTING THE CODE ---------------------------------------------
			ORG			0x00
			CLRF		HIG	
			CLRF		LOWE
			BSF			TRISB,RB0
			CLRF		COUNTER
			MOVLW		0xF0
			MOVWF		TRISD
			MOVLW		B'100'
			MOVWF		TRISE
;---------------- BUTTON SUBROUTINE ---------------------------------------------
BUTTON
	HI
			MOVLW		0x01
			MOVWF		HIG
			BTFSS		PORTB,RB0
			BRA			BACK
			CLRF		HIG
	LO
			BTFSC		PORTB,RB0
			BRA			BACK
			BRA			FUNCTION1
;--------------- DISPLAYING SUBROUTINE ---------------------------------------------
BACK
			MOVF		COUNTER,W
			ANDLW		0x0F
			MOVWF		PORTD
			MOVLW		0x01
			MOVWF		PORTE	
			CALL		TIMER0
			SWAPF		COUNTER,W
			ANDLW		0x0F
			MOVWF		PORTD
			MOVLW		0x02
			MOVWF		PORTE
			CALL		TIMER0
			MOVF		HIG,W
			XORLW		0x01
			BZ			HI
			BRA			LO
;--------------- SUBROUTINE FOR TESTING IF THE VALUES EXCEEDS THE RANGE (BCD(0-9))-------------------------
FUNCTION1
			MOVLW		0x01
			ADDWF		COUNTER,F
			MOVF		COUNTER,W	
			ANDLW		0x0F
			XORLW		0x0A
			BTFSS		STATUS,Z
			BRA			FUNCTION
			MOVLW		0x06			; ADDING 6 TO THE LOWEST NIBBLE 
			ADDWF		COUNTER,F
			SWAPF		COUNTER,W
			ANDLW		0x0F
			XORLW		0x0A
			BTFSC		STATUS,2
			CALL		FO
			BRA			FUNCTION
FO
			MOVLW		0x60			; ADDING 6 TO THE HIGHEST NIBBLE 
			ADDWF		COUNTER,F
			RETURN
;--------------------------------------
FUNCTION
			MOVF		COUNTER,W
			XORLW		0x00
			BTFSC		STATUS,Z
			CALL		FOO
			BRA			BUTTON
FOO
			BTFSC		STATUS,C
			CALL		FII
			RETURN
FII	
			CLRF		COUNTER
			CLRF		PORTD	
			RETURN
;----------------- TIMER0 SUBROUTINE FOR GENERATING TIME DELAY ------------------------------
TIMER0
			MOVLW		0x08			; PRESCALER IS NOT SET
			MOVWF		T0CON
			MOVLW		0x3C		
			MOVWF		TMR0H
			MOVLW		0xB0
			MOVWF		TMR0L			; TMR0H = 0x3C, TMR0L = 0xB0 => TMR0 COUNTS FROM = 15536 UNTIL 65536
			BCF			INTCON,TMR0IF
			BSF			T0CON,TMR0ON			
TEST
			BTFSS		INTCON,TMR0IF		; MONITORING THE STATE OF THE FLAG(TMR0IF)
			BRA			TEST
			BCF			INTCON,TMR0IF
			BCF			T0CON,T0CON
			RETURN
;--------------------------------------------------------------------------------------------------
			END
;---------------------------------------------------------------------------------------------------
