; ASM CODE FOR LOADING A BLOCK OF MEMORY LOCATION WITH VALUES 
; STARTING FROM ADDRESS 0x000 TO ADDRESS 0x009
; EACH LOCATION HAS A VALUE THAT CORRESPONDS TO EACH MEMORY LOCATION VALUE

			#include <p18f452.inc>
			CONFIG	WDT = OFF
			LIST	P = 18F452	
			RADIX	HEX
COUNTER		EQU		0x00F				; ASSIGN A NAME TO AN ADDRESS 0x00F
			ORG		0x00000
			CLRF	COUNTER,0			; CLEAR COUNTER
			LFSR	0, 0x000			; FSR0 HOLDS THE ADDRESS 0x000
BACK
			MOVF	COUNTER,W,0			; LOAD THE CONTENT OF COUNTER TO THE ADDRESS THAT FSR0 POINTS TO
			MOVWF	INDF0,0		
			INCF	COUNTER,F,0			; INCREMENT COUNTER
			INCF	FSR0L,F,0			; INCREMENT FRS0 TO POINT TO NEXT ADDRESS
			MOVF	FSR0L,W,0			; CHECK IF FSR0 REACHES 0x00A PR NOT
			XORLW	0x0A
			BNZ		BACK				; IF YES REPEAT PROCESS
			END