				#include <p18f452.inc>
				LIST	P = 18F452
				CONFIG	WDT = OFF
#define 		RS		LATC,RC0
#define 		RW		LATC,RC1
#define 		EN		LATC,RC2
COUNTER			EQU		0x000
				ORG		0x00512
LABEL			DB			"COUNTER : \0"
				ORG		0x00000
				GOTO	MAIN
				ORG		0x00008
				GOTO	INTERRUPT
MAIN
				CLRF	TRISD
				CLRF	COUNTER	
				MOVLW	0xF0
				MOVWF	TRISC
				CALL	LCD_CONFIGURE
				BSF		INTCON,GIE
				BSF		INTCON,PEIE
				BSF		PIE1, TMR1IE
				BCF		PIR1,TMR1IF
				MOVLW	0xB0
				MOVWF	T1CON
				CLRF	TMR1H
				CLRF	TMR1L
				BSF		T1CON,TMR1ON
				CALL	TABLE_READ
				GOTO	$
INTERRUPT
				BCF		PIR1,TMR1IF	
				MOVF	COUNTER,W
				XORLW	0x9A
				BZ		ONEHUND
				MOVF	COUNTER,W
				ANDLW	0x0F
				XORLW	0x0A
				BZ		TEN
RETU
				SWAPF	COUNTER,W
				ANDLW	0x0F
				ADDLW	0x30
				CALL	LCD_DATA
				MOVF	COUNTER,W
				ANDLW	0x0F		
				ADDLW	0x30
				CALL	LCD_DATA	
				INCF	COUNTER,F
				GOTO	FINI
ONEHUND
				CLRF	COUNTER
				GOTO	RETU
TEN
				MOVLW	0x06
				ADDWF	COUNTER,F
				GOTO	RETU				
FINI
				CLRF	TMR1H
				CLRF	TMR1L
				MOVLW	0x10
				CALL	LCD_COMMAND
				CALL	BUSY_FLAG
				MOVLW	0x10
				CALL	LCD_COMMAND
				CALL	BUSY_FLAG
				RETFIE
LCD_CONFIGURE
				CALL	LONG_DELAY
				MOVLW	0x38
				CALL	LCD_COMMAND
				CALL	LONG_DELAY
				MOVLW	0x01
				CALL	LCD_COMMAND
				CALL	LONG_DELAY
				MOVLW	0x0C
				CALL	LCD_COMMAND
				CALL	LONG_DELAY				
				RETURN
LCD_DATA
				MOVWF	LATD,0
				BSF		RS
				BCF		RW
				BSF		EN
				CALL	SHORT_DELAY
				BCF		EN
				CALL 	BUSY_FLAG
				RETURN
LCD_COMMAND
				MOVWF	LATD,0
				BCF		RS
				BCF		RW
				BSF		EN
				CALL	SHORT_DELAY
				BCF		EN
				RETURN

SHORT_DELAY
				MOVLW	0x40
				MOVWF	T0CON
				MOVLW	0x1F
				MOVWF	TMR0L
				BCF		INTCON,TMR0IF
				BSF		T0CON,TMR0ON
KEEP
				BTFSS	INTCON,TMR0IF
				GOTO	KEEP
				BCF		INTCON,TMR0IF
				BCF		T0CON,TMR0ON
				RETURN
LONG_DELAY
				MOVLW	0x47
				MOVWF	T0CON
				CLRF	TMR0L
				BCF		INTCON,TMR0IF
				BSF		T0CON,TMR0ON
KEEP_1
				BTFSS	INTCON,TMR0IF
				GOTO	KEEP_1
				BCF		INTCON,TMR0IF
				BCF		T0CON,TMR0ON
				RETURN
BUSY_FLAG
				BSF		TRISD,TRISD7
				BCF		RS			
				BSF		RW
REPEAT
				BSF		EN
				CALL	SHORT_DELAY
				BCF		EN
				BTFSC	PORTD,RD7
				GOTO	REPEAT
				BCF		TRISD,TRISD7
				RETURN		
TABLE_READ
				MOVLW	0x05
				MOVWF	TBLPTRH
				MOVLW	0x12
				MOVWF	TBLPTRL
PROCESS
				TBLRD*
				MOVF	TABLAT,W
				XORLW	'\0'
				BZ		FINISH
				MOVF	TABLAT,W
				CALL	LCD_DATA
				INCF	TBLPTRL,F
				GOTO	PROCESS
FINISH
				RETURN
				END
			