				#include <p18f452.inc>
				LIST	P = 18F452
				CONFIG	WDT = OFF
#define 		RS		LATC,RC0
#define 		RW		LATC,RC1
#define 		EN		LATC,RC2
COUNTER			EQU		0x000
STATE			EQU		0x001
				ORG		0x00512
				ORG		0x00000
				GOTO	MAIN
				ORG		0x00008	
				GOTO	INTERRUPT
MAIN
				CLRF	TRISD,0		
				CLRF	STATE,0	
				MOVLW	0xFF
				MOVWF	COUNTER,0
				MOVLW	0xF0
				MOVWF	TRISC,0
				CALL	LCD_CONFIGURE
				BSF		INTCON,GIE,0
				BSF		INTCON,INT0IE,0
				BCF		INTCON,INT0IF,0
				GOTO	SUPER_LOOP
				RETFIE
RESETS
				CLRF	COUNTER,0
DISPLAY
				MOVLW	0x31
				CALL	LCD_DATA
				RETURN
INTERRUPT
				BTFSC	INTCON,INT0IF,0
				GOTO	BUTTON_PRESS
				RETFIE
BUTTON_PRESS
				BCF		INTCON,INT0IF,0
				BSF		STATE,0,0
				BTG		LATC,LATC3
				INCF	COUNTER,F,0
				MOVF	COUNTER,W,0
				XORLW	0x10
				BZ		HERE
				RETFIE
HERE
				CLRF	COUNTER,0
				RETFIE
LCD_CONFIGURE
				CALL	LONG_DELAY
				MOVLW	0x38
				CALL	LCD_COMMAND
				CALL	LONG_DELAY
				MOVLW	0x01
				CALL	LCD_COMMAND
				CALL	LONG_DELAY
				MOVLW	0x0F
				CALL	LCD_COMMAND
				CALL	LONG_DELAY				
				RETURN
LCD_DATA
				MOVWF	LATD,0
				BSF		RS
				BCF		RW
				BSF		EN
				CALL	SHORT_DELAY
				BCF		EN
				CALL 	BUSY_FLAG
				RETURN
LCD_COMMAND
				MOVWF	LATD,0
				BCF		RS
				BCF		RW
				BSF		EN
				CALL	SHORT_DELAY
				BCF		EN
				RETURN

SHORT_DELAY
				MOVLW	0x40
				MOVWF	T0CON
				MOVLW	0x1F
				MOVWF	TMR0L
				BCF		INTCON,TMR0IF
				BSF		T0CON,TMR0ON
KEEP
				BTFSS	INTCON,TMR0IF
				GOTO	KEEP
				BCF		INTCON,TMR0IF
				BCF		T0CON,TMR0ON
				RETURN
LONG_DELAY
				MOVLW	0x47
				MOVWF	T0CON
				CLRF	TMR0L
				BCF		INTCON,TMR0IF
				BSF		T0CON,TMR0ON
KEEP_1
				BTFSS	INTCON,TMR0IF
				GOTO	KEEP_1
				BCF		INTCON,TMR0IF
				BCF		T0CON,TMR0ON
				RETURN
BUSY_FLAG
				BSF		TRISD,TRISD7
				BCF		RS			
				BSF		RW
REPEAT
				BCF		EN
				CALL	SHORT_DELAY
				BSF		EN
				BTFSC	PORTD,RD7
				GOTO	REPEAT
				BCF		TRISD,TRISD7
				RETURN		
SUPER_LOOP
				MOVF	STATE,W,0
				XORLW	0x01
				BZ		GOT
				GOTO	SUPER_LOOP
GOT
				CLRF	STATE,0
				MOVLW	0x01
				CALL	LCD_COMMAND
				CALL	LONG_DELAY
				MOVF	COUNTER,W,0
				ADDLW	0x80
				CALL	LCD_COMMAND
				CALL	BUSY_FLAG
				CALL	DISPLAY
				GOTO	SUPER_LOOP
				END
			